---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta-gitlab-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beta-gitlab-runner
      env: beta
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: beta-gitlab-runner
        env: beta
    spec:
      containers:
      - name: beta-gitlab-runner
        imagePullPolicy: Always
        image: gitlab/gitlab-runner:latest
        volumeMounts:
          - name: conf
            mountPath: /etc/gitlab-runner
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 1000m
            memory: 1Gi
      volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: beta-gitlab-runner
