apiVersion: batch/v1
kind: Job
metadata:
  name: gitlab-runner-init-2
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: gitlab-runner-init-2
        image: busybox:latest
        args: ["sed -i  -e 's|    volumes =.*|    volumes = [\"/cache\", \"/var/run/docker.sock:/run/docker.sock\"]|g' -e '/^    volumes/a\    network_mode = \"host\"' /etc/gitlab-runner/config.toml"]
        volumeMounts:
          - name: conf
            mountPath: /etc/gitlab-runner
      restartPolicy: Never
      volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: beta-gitlab-runner
  backoffLimit: 1

