---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-runner-conf
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 10Mi
